drop database employees;

create database employees;

use employees;

create table EMPLOYEE (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
FIRSTNAME VARCHAR(10),
LASTNAME VARCHAR(20),
BIRTHDAY DATE,
GENDER VARCHAR(6),
HIREDATE TIMESTAMP,
SALARY DOUBLE,
CHILDREN INT);

commit;